[package]
name = "typsium-rs"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
csv = "1.3.1"
logos = "0.15.0"
once_cell = "1.21.3"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
typst-wasm-protocol = "0.0.2"
